apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp 
    spec:
      subdomain: mysql-service
      containers:
      - name: nodeserver-myapp
        #image: cloud.canister.io:5000/pasrdfffsas/myapp:latest
        image: marek21sk/myapp_v3:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST 
          value: mysql-service # MySQL hostname
        - name: DB_PORT
          value: "3306" # MySQL port
        imagePullPolicy: Always
      imagePullSecrets:
        - name:  regcred # secret that K8s uses to access image
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 # počkajme 5 sekúnd, aby sme sa uistili, že nový kontajner sa môže spustiť
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 80 # expose the service on port 80
    targetPort: 3000 # our NodeJS app listens on port 3000
    nodePort: 31110