apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql # názov kontajnera 
        image: mysql:latest # určuje image, z ktorého sa má kontajner vytvoriť 
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD # premenné, ktoré sa majú pridať do kontajnera 
          valueFrom: # prístup ku secrets, ktoré sú uložené v Kubernetes
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username 
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password                                     
        volumeMounts:
        - name:  mysql-persistent-storage
          mountPath:  /var/lib/mysql
      volumes: 
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  ports:
    - port: 3306 # všeobecne používaný port na komunikáciu s MySQL databázou
      targetPort: 3306 # naša databáza počúva na porte 3306 
      nodePort: 31306 # port, na ktorom bude naša služba počúvať v prípade, že by bolo možné pristupovať k aplikácii pomocou IP adresy a portu
  selector:
    app: mysql
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi # kapacita PV
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Kubernetes/database_data" # cesta kde sa má databáza ukladať 
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi # 250MB, ktoré PVC vyžaduje dostupné, pre ukladanie do PC