# Tento ClusterIssues podľa "describe" funguje, len čaká na platný certifikát a cestu
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: myapp-ssl-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: marek.pastor@h10s.eu # Zmenené na môj email
    privateKeySecretRef:
      name: myapp-ssl-prod-key