replicaCount: 1
image:
  repository: marek21sk/myapp_v11
  tag: "latest"
  pullPolicy: Always
service:
  type: NodePort
  port: 8080
  targetPort: 3000
  nodePort: 31120
  protocol: TCP
  name: myapp-service
imagePullSecretsName: regcred